<?php
/**
 * TempMail PHP Backend Installer
 * 
 * This script helps you set up the TempMail backend on cPanel/shared hosting.
 * Access this file in your browser to run the installation wizard.
 * 
 * IMPORTANT: Delete this file after installation for security!
 */

session_start();

// Installation steps
$steps = [
    1 => 'Requirements Check',
    2 => 'Database Configuration',
    3 => 'Create Database Tables',
    4 => 'Application Settings',
    5 => 'Complete'
];

$currentStep = isset($_POST['step']) ? (int)$_POST['step'] : 1;
$errors = [];
$success = [];

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($currentStep) {
        case 2:
            // Test database connection
            $dbHost = trim($_POST['db_host'] ?? 'localhost');
            $dbName = trim($_POST['db_name'] ?? '');
            $dbUser = trim($_POST['db_user'] ?? '');
            $dbPass = $_POST['db_pass'] ?? '';
            
            try {
                $pdo = new PDO(
                    "mysql:host={$dbHost};charset=utf8mb4",
                    $dbUser,
                    $dbPass,
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
                );
                
                // Check if database exists, create if not
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$dbName}`");
                
                // Store in session for next step
                $_SESSION['db'] = [
                    'host' => $dbHost,
                    'name' => $dbName,
                    'user' => $dbUser,
                    'pass' => $dbPass
                ];
                
                $success[] = "Database connection successful!";
                $currentStep = 3;
            } catch (PDOException $e) {
                $errors[] = "Database connection failed: " . $e->getMessage();
            }
            break;
            
        case 3:
            // Create database tables
            if (!isset($_SESSION['db'])) {
                $errors[] = "Database configuration not found. Please go back to step 2.";
                $currentStep = 2;
                break;
            }
            
            try {
                $db = $_SESSION['db'];
                $pdo = new PDO(
                    "mysql:host={$db['host']};dbname={$db['name']};charset=utf8mb4",
                    $db['user'],
                    $db['pass'],
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
                );
                
                // Read and execute schema
                $schemaPath = __DIR__ . '/schema.sql';
                if (!file_exists($schemaPath)) {
                    $errors[] = "schema.sql file not found! Please upload it to the same directory.";
                    break;
                }
                
                $schema = file_get_contents($schemaPath);
                
                // Split by semicolon and execute each statement
                $statements = array_filter(
                    array_map('trim', explode(';', $schema)),
                    fn($s) => !empty($s)
                );
                
                foreach ($statements as $statement) {
                    $pdo->exec($statement);
                }
                
                $success[] = "Database tables created successfully!";
                $currentStep = 4;
            } catch (PDOException $e) {
                $errors[] = "Failed to create tables: " . $e->getMessage();
            }
            break;
            
        case 4:
            // Generate config file
            if (!isset($_SESSION['db'])) {
                $errors[] = "Database configuration not found. Please go back to step 2.";
                $currentStep = 2;
                break;
            }
            
            $db = $_SESSION['db'];
            $siteName = trim($_POST['site_name'] ?? 'TempMail');
            $siteUrl = trim($_POST['site_url'] ?? '');
            $jwtSecret = $_POST['jwt_secret'] ?? bin2hex(random_bytes(32));
            $corsOrigin = trim($_POST['cors_origin'] ?? '*');
            $smtpHost = trim($_POST['smtp_host'] ?? '');
            $smtpPort = (int)($_POST['smtp_port'] ?? 587);
            $smtpUser = trim($_POST['smtp_user'] ?? '');
            $smtpPass = $_POST['smtp_pass'] ?? '';
            $smtpFrom = trim($_POST['smtp_from'] ?? '');
            
            // Generate config.php content
            $configContent = <<<PHP
<?php
/**
 * TempMail PHP Backend Configuration
 * Generated by installer on {$date}
 */

// Database Configuration
define('DB_HOST', '{$db['host']}');
define('DB_NAME', '{$db['name']}');
define('DB_USER', '{$db['user']}');
define('DB_PASS', '{$db['pass']}');

// Application Settings
define('SITE_NAME', '{$siteName}');
define('SITE_URL', '{$siteUrl}');

// JWT Configuration
define('JWT_SECRET', '{$jwtSecret}');
define('JWT_EXPIRY', 86400 * 7); // 7 days

// CORS Configuration
define('CORS_ORIGIN', '{$corsOrigin}');

// SMTP Configuration (for sending emails)
define('SMTP_HOST', '{$smtpHost}');
define('SMTP_PORT', {$smtpPort});
define('SMTP_USER', '{$smtpUser}');
define('SMTP_PASS', '{$smtpPass}');
define('SMTP_FROM', '{$smtpFrom}');
define('SMTP_ENCRYPTION', 'tls'); // 'tls' or 'ssl'

// IMAP Configuration (for receiving emails)
define('IMAP_HOST', '');
define('IMAP_PORT', 993);
define('IMAP_USER', '');
define('IMAP_PASS', '');

// Storage Configuration
define('STORAGE_PATH', __DIR__ . '/storage');
define('MAX_UPLOAD_SIZE', 10 * 1024 * 1024); // 10MB

// Rate Limiting
define('RATE_LIMIT_REQUESTS', 100);
define('RATE_LIMIT_WINDOW', 60); // seconds

// Email Settings
define('DEFAULT_EMAIL_EXPIRY_HOURS', 24);
define('MAX_TEMP_EMAILS_PER_USER', 10);

// Security
define('BCRYPT_COST', 12);
define('SESSION_LIFETIME', 86400 * 7); // 7 days
PHP;

            $date = date('Y-m-d H:i:s');
            $configContent = str_replace('{$date}', $date, $configContent);
            
            // Write config file
            $configPath = __DIR__ . '/config.php';
            if (file_put_contents($configPath, $configContent) === false) {
                $errors[] = "Failed to write config.php. Please check directory permissions.";
                break;
            }
            
            // Create storage directories
            $storageDirs = [
                __DIR__ . '/storage',
                __DIR__ . '/storage/avatars',
                __DIR__ . '/storage/attachments',
                __DIR__ . '/storage/banners',
                __DIR__ . '/storage/backups'
            ];
            
            foreach ($storageDirs as $dir) {
                if (!is_dir($dir)) {
                    mkdir($dir, 0755, true);
                }
            }
            
            // Create .htaccess in storage to protect files
            $storageHtaccess = <<<HTACCESS
# Protect storage directory
Options -Indexes

# Only allow specific file types to be accessed directly
<FilesMatch "\.(jpg|jpeg|png|gif|webp|svg|ico|pdf)$">
    Order allow,deny
    Allow from all
</FilesMatch>

# Deny access to everything else
<FilesMatch "^(?!.*\.(jpg|jpeg|png|gif|webp|svg|ico|pdf)$).*$">
    Order allow,deny
    Deny from all
</FilesMatch>
HTACCESS;
            file_put_contents(__DIR__ . '/storage/.htaccess', $storageHtaccess);
            
            $success[] = "Configuration saved successfully!";
            $_SESSION['install_complete'] = true;
            $currentStep = 5;
            break;
    }
}

// Check requirements
function checkRequirements(): array {
    $requirements = [];
    
    // PHP Version
    $requirements['PHP 8.0+'] = version_compare(PHP_VERSION, '8.0.0', '>=');
    
    // Extensions
    $requirements['PDO Extension'] = extension_loaded('pdo');
    $requirements['PDO MySQL'] = extension_loaded('pdo_mysql');
    $requirements['JSON Extension'] = extension_loaded('json');
    $requirements['OpenSSL Extension'] = extension_loaded('openssl');
    $requirements['Mbstring Extension'] = extension_loaded('mbstring');
    
    // Optional but recommended
    $requirements['IMAP Extension (optional)'] = extension_loaded('imap');
    $requirements['cURL Extension'] = extension_loaded('curl');
    
    // Writeable directories
    $requirements['Directory Writeable'] = is_writable(__DIR__);
    
    return $requirements;
}

$requirements = checkRequirements();
$allRequirementsMet = !in_array(false, array_slice($requirements, 0, 5)); // Only required ones

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TempMail Installer</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #0f0f23 0%, #1a1a2e 50%, #16213e 100%);
            color: #e4e4e7;
            min-height: 100vh;
            padding: 2rem;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
        }
        
        .header {
            text-align: center;
            margin-bottom: 2rem;
        }
        
        .header h1 {
            font-size: 2.5rem;
            background: linear-gradient(135deg, #14b8a6, #8b5cf6);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.5rem;
        }
        
        .header p {
            color: #a1a1aa;
        }
        
        .steps {
            display: flex;
            justify-content: space-between;
            margin-bottom: 2rem;
            padding: 0 1rem;
        }
        
        .step {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 0.5rem;
        }
        
        .step-number {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            background: #27272a;
            border: 2px solid #3f3f46;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
        }
        
        .step.active .step-number {
            background: linear-gradient(135deg, #14b8a6, #8b5cf6);
            border-color: #14b8a6;
        }
        
        .step.completed .step-number {
            background: #22c55e;
            border-color: #22c55e;
        }
        
        .step-label {
            font-size: 0.75rem;
            color: #71717a;
            text-align: center;
        }
        
        .step.active .step-label {
            color: #14b8a6;
        }
        
        .card {
            background: rgba(39, 39, 42, 0.8);
            border: 1px solid #3f3f46;
            border-radius: 1rem;
            padding: 2rem;
            backdrop-filter: blur(10px);
        }
        
        .card h2 {
            margin-bottom: 1.5rem;
            color: #fafafa;
        }
        
        .form-group {
            margin-bottom: 1.5rem;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            color: #a1a1aa;
            font-size: 0.875rem;
        }
        
        .form-group input {
            width: 100%;
            padding: 0.75rem 1rem;
            border: 1px solid #3f3f46;
            border-radius: 0.5rem;
            background: #18181b;
            color: #fafafa;
            font-size: 1rem;
        }
        
        .form-group input:focus {
            outline: none;
            border-color: #14b8a6;
        }
        
        .form-group small {
            display: block;
            margin-top: 0.25rem;
            color: #71717a;
            font-size: 0.75rem;
        }
        
        .btn {
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
            padding: 0.75rem 1.5rem;
            border: none;
            border-radius: 0.5rem;
            font-size: 1rem;
            cursor: pointer;
            transition: all 0.2s;
        }
        
        .btn-primary {
            background: linear-gradient(135deg, #14b8a6, #0d9488);
            color: white;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(20, 184, 166, 0.4);
        }
        
        .btn-secondary {
            background: #3f3f46;
            color: #e4e4e7;
        }
        
        .requirements-list {
            display: grid;
            gap: 0.75rem;
        }
        
        .requirement {
            display: flex;
            align-items: center;
            gap: 0.75rem;
            padding: 0.75rem 1rem;
            background: #18181b;
            border-radius: 0.5rem;
        }
        
        .requirement-icon {
            width: 24px;
            height: 24px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 0.75rem;
        }
        
        .requirement-icon.pass {
            background: #22c55e;
        }
        
        .requirement-icon.fail {
            background: #ef4444;
        }
        
        .alert {
            padding: 1rem;
            border-radius: 0.5rem;
            margin-bottom: 1rem;
        }
        
        .alert-error {
            background: rgba(239, 68, 68, 0.2);
            border: 1px solid #ef4444;
            color: #fca5a5;
        }
        
        .alert-success {
            background: rgba(34, 197, 94, 0.2);
            border: 1px solid #22c55e;
            color: #86efac;
        }
        
        .actions {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
        }
        
        .complete-message {
            text-align: center;
            padding: 2rem;
        }
        
        .complete-icon {
            width: 80px;
            height: 80px;
            background: linear-gradient(135deg, #22c55e, #16a34a);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 1.5rem;
            font-size: 2.5rem;
        }
        
        .warning-box {
            background: rgba(245, 158, 11, 0.2);
            border: 1px solid #f59e0b;
            color: #fcd34d;
            padding: 1rem;
            border-radius: 0.5rem;
            margin-top: 1.5rem;
        }
        
        .code-block {
            background: #18181b;
            padding: 1rem;
            border-radius: 0.5rem;
            font-family: monospace;
            margin-top: 0.5rem;
            overflow-x: auto;
        }
        
        .grid-2 {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 1rem;
        }
        
        @media (max-width: 640px) {
            .grid-2 {
                grid-template-columns: 1fr;
            }
            
            .steps {
                flex-wrap: wrap;
                gap: 1rem;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📧 TempMail Installer</h1>
            <p>Self-Hosted PHP Backend Setup Wizard</p>
        </div>
        
        <div class="steps">
            <?php foreach ($steps as $num => $label): ?>
            <div class="step <?php echo $num === $currentStep ? 'active' : ($num < $currentStep ? 'completed' : ''); ?>">
                <div class="step-number"><?php echo $num < $currentStep ? '✓' : $num; ?></div>
                <div class="step-label"><?php echo $label; ?></div>
            </div>
            <?php endforeach; ?>
        </div>
        
        <?php if (!empty($errors)): ?>
        <div class="alert alert-error">
            <?php foreach ($errors as $error): ?>
            <p><?php echo htmlspecialchars($error); ?></p>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        
        <?php if (!empty($success)): ?>
        <div class="alert alert-success">
            <?php foreach ($success as $msg): ?>
            <p><?php echo htmlspecialchars($msg); ?></p>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        
        <div class="card">
            <?php if ($currentStep === 1): ?>
            <!-- Step 1: Requirements Check -->
            <h2>Step 1: Requirements Check</h2>
            <p style="margin-bottom: 1.5rem; color: #a1a1aa;">
                Let's make sure your server meets all the requirements.
            </p>
            
            <div class="requirements-list">
                <?php foreach ($requirements as $name => $passed): ?>
                <div class="requirement">
                    <div class="requirement-icon <?php echo $passed ? 'pass' : 'fail'; ?>">
                        <?php echo $passed ? '✓' : '✗'; ?>
                    </div>
                    <span><?php echo htmlspecialchars($name); ?></span>
                </div>
                <?php endforeach; ?>
            </div>
            
            <div class="actions">
                <?php if ($allRequirementsMet): ?>
                <form method="post">
                    <input type="hidden" name="step" value="2">
                    <button type="submit" class="btn btn-primary">Continue →</button>
                </form>
                <?php else: ?>
                <p style="color: #ef4444;">Please resolve the failed requirements before continuing.</p>
                <?php endif; ?>
            </div>
            
            <?php elseif ($currentStep === 2): ?>
            <!-- Step 2: Database Configuration -->
            <h2>Step 2: Database Configuration</h2>
            <p style="margin-bottom: 1.5rem; color: #a1a1aa;">
                Enter your MySQL database credentials. You can find these in cPanel under "MySQL Databases".
            </p>
            
            <form method="post">
                <input type="hidden" name="step" value="2">
                
                <div class="grid-2">
                    <div class="form-group">
                        <label for="db_host">Database Host</label>
                        <input type="text" id="db_host" name="db_host" value="localhost" required>
                        <small>Usually "localhost" for cPanel hosting</small>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_name">Database Name</label>
                        <input type="text" id="db_name" name="db_name" placeholder="cpaneluser_tempmail" required>
                        <small>The database you created in cPanel</small>
                    </div>
                </div>
                
                <div class="grid-2">
                    <div class="form-group">
                        <label for="db_user">Database Username</label>
                        <input type="text" id="db_user" name="db_user" placeholder="cpaneluser_dbuser" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_pass">Database Password</label>
                        <input type="password" id="db_pass" name="db_pass" required>
                    </div>
                </div>
                
                <div class="actions">
                    <button type="submit" class="btn btn-primary">Test Connection & Continue →</button>
                </div>
            </form>
            
            <?php elseif ($currentStep === 3): ?>
            <!-- Step 3: Create Tables -->
            <h2>Step 3: Create Database Tables</h2>
            <p style="margin-bottom: 1.5rem; color: #a1a1aa;">
                We'll now create all the necessary database tables for TempMail.
            </p>
            
            <form method="post">
                <input type="hidden" name="step" value="3">
                
                <p>This will create the following tables:</p>
                <div class="code-block">
                    users, profiles, domains, temp_emails, received_emails,<br>
                    email_attachments, user_roles, app_settings, blogs,<br>
                    subscription_tiers, user_subscriptions, and more...
                </div>
                
                <div class="actions">
                    <button type="submit" class="btn btn-primary">Create Tables →</button>
                </div>
            </form>
            
            <?php elseif ($currentStep === 4): ?>
            <!-- Step 4: Application Settings -->
            <h2>Step 4: Application Settings</h2>
            <p style="margin-bottom: 1.5rem; color: #a1a1aa;">
                Configure your application settings and SMTP for sending emails.
            </p>
            
            <form method="post">
                <input type="hidden" name="step" value="4">
                
                <div class="grid-2">
                    <div class="form-group">
                        <label for="site_name">Site Name</label>
                        <input type="text" id="site_name" name="site_name" value="TempMail" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="site_url">Site URL</label>
                        <input type="url" id="site_url" name="site_url" placeholder="https://yourdomain.com" required>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="cors_origin">CORS Origin</label>
                    <input type="text" id="cors_origin" name="cors_origin" value="*" placeholder="https://yourdomain.com">
                    <small>Use * for any origin, or specify your frontend URL</small>
                </div>
                
                <div class="form-group">
                    <label for="jwt_secret">JWT Secret Key</label>
                    <input type="text" id="jwt_secret" name="jwt_secret" value="<?php echo bin2hex(random_bytes(32)); ?>">
                    <small>Auto-generated secure key for JWT tokens</small>
                </div>
                
                <h3 style="margin: 2rem 0 1rem; color: #fafafa;">SMTP Settings (Optional)</h3>
                
                <div class="grid-2">
                    <div class="form-group">
                        <label for="smtp_host">SMTP Host</label>
                        <input type="text" id="smtp_host" name="smtp_host" placeholder="mail.yourdomain.com">
                    </div>
                    
                    <div class="form-group">
                        <label for="smtp_port">SMTP Port</label>
                        <input type="number" id="smtp_port" name="smtp_port" value="587">
                    </div>
                </div>
                
                <div class="grid-2">
                    <div class="form-group">
                        <label for="smtp_user">SMTP Username</label>
                        <input type="text" id="smtp_user" name="smtp_user" placeholder="noreply@yourdomain.com">
                    </div>
                    
                    <div class="form-group">
                        <label for="smtp_pass">SMTP Password</label>
                        <input type="password" id="smtp_pass" name="smtp_pass">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="smtp_from">From Email</label>
                    <input type="email" id="smtp_from" name="smtp_from" placeholder="noreply@yourdomain.com">
                </div>
                
                <div class="actions">
                    <button type="submit" class="btn btn-primary">Save & Complete →</button>
                </div>
            </form>
            
            <?php elseif ($currentStep === 5): ?>
            <!-- Step 5: Complete -->
            <div class="complete-message">
                <div class="complete-icon">🎉</div>
                <h2>Installation Complete!</h2>
                <p style="color: #a1a1aa; margin: 1rem 0;">
                    Your TempMail PHP backend has been installed successfully.
                </p>
                
                <div class="warning-box">
                    <strong>⚠️ Security Warning:</strong><br>
                    Please delete this <code>install.php</code> file immediately for security!
                    <div class="code-block">rm install.php</div>
                </div>
                
                <div style="margin-top: 2rem; text-align: left;">
                    <h3 style="margin-bottom: 1rem;">Next Steps:</h3>
                    <ol style="color: #a1a1aa; padding-left: 1.5rem; line-height: 2;">
                        <li>Update your frontend's <code>.env</code> file with:</li>
                    </ol>
                    <div class="code-block">
VITE_PHP_API_URL=https://yourdomain.com/api
                    </div>
                    <ol start="2" style="color: #a1a1aa; padding-left: 1.5rem; line-height: 2; margin-top: 1rem;">
                        <li>Create an admin user by visiting <code>/auth</code> and signing up</li>
                        <li>Run this SQL to make yourself an admin:</li>
                    </ol>
                    <div class="code-block">
INSERT INTO user_roles (user_id, role) <br>
SELECT id, 'admin' FROM users WHERE email = 'your@email.com';
                    </div>
                    <ol start="4" style="color: #a1a1aa; padding-left: 1.5rem; line-height: 2; margin-top: 1rem;">
                        <li>Add your email domains in the admin panel</li>
                        <li>Configure IMAP settings for receiving emails</li>
                    </ol>
                </div>
                
                <div class="actions" style="justify-content: center; margin-top: 2rem;">
                    <a href="/" class="btn btn-primary">Go to Homepage →</a>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
